#!/usr/bin/env bash

# autor: wellyton-xs <wellyton.offcer@gmail.com>
# nome: comp.sh
# objetivo: automatizar compilação c
# obs: caso necessário edite os diretórios
#      das variáveis $src e $target
# modo de uso:
# ./comp <src> <target>

#gcc "$src/$1" -o "$target/$2"

src="./src"
target="./target"

print(){
	printf '%s\n' "$1"
}

HELP(){
	print "USAGE: comp [options]

		options:
			h || --help - show help message

			l || list - list lang support
	"
}

LIST(){
	print "LANGUAGES: 
		c


		OBS: more languages comming soon ;) 
	"
}

COMPILE(){
	print "start compilation!"
	for file in "$src"/*"$extension"; do
	    filename=$(basename "$file")
	    print "get: $filename"
	    filename_without_extension="${filename%$extension}"
	    print "get target: $filename_without_extension"
	    print "-> compiling: $filename"
	    gcc "$file" -o "$target/$filename_without_extension"
	    print "% compiled: $target/$filename_without_extension"
	done
}

case "$1" in
	"")
		extension="c"
	;;

	h | help)
		HELP
	;;

	l | list)
		LIST
	;;
	
	c)
		extension=".c"
		COMPILE
	;;

	*)
		print "program exit with a error $?"
		exit 1
	;;
esac



